<?php
/**
 * @file
 * Code for the DKAN Harvest Dashboard feature.
 */

include_once 'dkan_harvest_dashboard.features.inc';

/**
 * Implements hook_permission().
 */
function dkan_harvest_dashboard_permission() {
  return array(
    'admininster harvest' => array(
      'title' => t('Administrate harvest sources and datasets'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function dkan_harvest_dashboard_menu() {
  $items = array();
  $items['admin/dkan/harvest/dashboard'] = array(
    'title' => 'DKAN Harvest Dashboard',
    'access callback' => 'user_access',
    'access arguments' => array('admininster harvest'),
    'page callback' => 'dkan_harvest_dashboard_sources_page',
  );
  
  $items['admin/dkan/harvest/dashboard/sources'] = array(
    'title' => 'Sources',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access callback' => 'user_access',
    'access arguments' => array('admininster harvest'),
    'weight' => -10,
    'page callback' => 'dkan_harvest_dashboard_sources_page',
  );

  $items['admin/dkan/harvest/dashboard/datasets'] = array(
    'title' => 'Datasets',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'user_access',
    'access arguments' => array('admininster harvest'),
    'weight' => 1,
    'page callback' => 'dkan_harvest_dashboard_datasets_page',
  );  
  return $items;
}

/**
 * Dataset list page callback
 */
function dkan_harvest_dashboard_sources_page() {
  return views_embed_view('dkan_harvest_dashboard', 'harvest_sources');
}

/**
 * Sources list page callback
 */
function dkan_harvest_dashboard_datasets_page() {
  return views_embed_view('dkan_harvest_datasets', 'harvest_datasets');
}

function dkan_harvest_dashboard_form_alter(&$form, $form_state, $form_id) {
  if(  $form_id == 'views_exposed_form' 
    && $form_state['view'] 
    && $form_state['view']->name ) {

    $module_path = drupal_get_path('module', 'dkan_harvest_dashboard');
    drupal_add_css( $module_path . '/dkan_harvest_dashboard.css');
    $form['created']['max']['#title'] = '';
    $form['changed']['max']['#title'] = '';
    $form['created']['min']['#attributes']['placeholder'] = t('From');
    $form['created']['max']['#attributes']['placeholder'] = t('To');
    $form['changed']['min']['#attributes']['placeholder'] = t('From');
    $form['changed']['max']['#attributes']['placeholder'] = t('To');
  }
}
